/** A valid red 2x3 baseline RGB JPEG generated by Pillow. */
export function rgbJpeg(): Uint8Array {
	const hex = [
		"ffd8ffe000104a46494600010100000100010000ffdb004300100b0c0e0c0a100e0d0e12",
		"11101318281a181616183123251d283a333d3c3933383740485c4e404457453738506d51",
		"575f626768673e4d71797064785c656763ffdb0043011112121815182f1a1a2f63423842",
		"636363636363636363636363636363636363636363636363636363636363636363636363",
		"6363636363636363636363636363ffc00011080003000203012200021101031101ffc400",
		"1500010100000000000000000000000000000005ffc40014100100000000000000000000",
		"000000000000ffc4001501010100000000000000000000000000000506ffc40014110100",
		"000000000000000000000000000000ffda000c03010002110311003f008a00b5e3ffd9",
	].join("")
	const bytes = new Uint8Array(hex.length / 2)
	for (let index = 0; index < bytes.length; index += 1) {
		bytes[index] = Number.parseInt(hex.slice(index * 2, index * 2 + 2), 16)
	}

	return bytes
}

/** A structurally valid 2x3 baseline grayscale JPEG for parser-only tests. */
export function grayscaleJpeg(): Uint8Array {
	return Uint8Array.from([
		0xff,
		0xd8,
		0xff,
		0xdb,
		0x00,
		0x43,
		0x00,
		...Array<number>(64).fill(1),
		0xff,
		0xc4,
		0x00,
		0x14,
		0x00,
		0x01,
		...Array<number>(15).fill(0),
		0x00,
		0xff,
		0xc4,
		0x00,
		0x14,
		0x10,
		0x01,
		...Array<number>(15).fill(0),
		0x00,
		0xff,
		0xc0,
		0x00,
		0x0b,
		0x08,
		0x00,
		0x03,
		0x00,
		0x02,
		0x01,
		0x01,
		0x11,
		0x00,
		0xff,
		0xda,
		0x00,
		0x08,
		0x01,
		0x01,
		0x00,
		0x00,
		0x3f,
		0x00,
		0x01,
		0xff,
		0xd9,
	])
}
